import type { ExerciseSeedRow } from './types';

export const STARTER_EXERCISE_SEED_VERSION = 'starter-v1';
export const STARTER_EXERCISE_SOURCE_NAME =
  'Fitness Tracker Starter Exercise Set';
export const STARTER_EXERCISE_LICENSE = 'CC0-1.0';

export const STARTER_EXERCISES = [
  {
    id: 'exercise-barbell-bench-press',
    slug: 'barbell-bench-press',
    nameZh: '杠铃卧推',
    nameEn: 'Barbell Bench Press',
    type: 'strength',
    primaryMuscleGroup: 'chest',
    secondaryMuscleGroups: ['shoulders', 'arms'],
    equipment: 'barbell',
    description: '平板卧推，主要训练胸部推举力量。',
    imageUri: null,
    sourceName: STARTER_EXERCISE_SOURCE_NAME,
    sourceReference: STARTER_EXERCISE_SEED_VERSION,
    license: STARTER_EXERCISE_LICENSE,
    status: 'active',
    createdAt: '2026-07-15T00:00:00.000Z',
    updatedAt: '2026-07-15T00:00:00.000Z',
  },
  {
    id: 'exercise-lat-pulldown',
    slug: 'lat-pulldown',
    nameZh: '高位下拉',
    nameEn: 'Lat Pulldown',
    type: 'strength',
    primaryMuscleGroup: 'back',
    secondaryMuscleGroups: ['arms'],
    equipment: 'machine',
    description: '垂直下拉动作，主要训练背部。',
    imageUri: null,
    sourceName: STARTER_EXERCISE_SOURCE_NAME,
    sourceReference: STARTER_EXERCISE_SEED_VERSION,
    license: STARTER_EXERCISE_LICENSE,
    status: 'active',
    createdAt: '2026-07-15T00:00:00.000Z',
    updatedAt: '2026-07-15T00:00:00.000Z',
  },
  {
    id: 'exercise-dumbbell-shoulder-press',
    slug: 'dumbbell-shoulder-press',
    nameZh: '哑铃肩推',
    nameEn: 'Dumbbell Shoulder Press',
    type: 'strength',
    primaryMuscleGroup: 'shoulders',
    secondaryMuscleGroups: ['arms'],
    equipment: 'dumbbell',
    description: '坐姿或站姿向上推举哑铃，主要训练肩部。',
    imageUri: null,
    sourceName: STARTER_EXERCISE_SOURCE_NAME,
    sourceReference: STARTER_EXERCISE_SEED_VERSION,
    license: STARTER_EXERCISE_LICENSE,
    status: 'active',
    createdAt: '2026-07-15T00:00:00.000Z',
    updatedAt: '2026-07-15T00:00:00.000Z',
  },
  {
    id: 'exercise-leg-press',
    slug: 'leg-press',
    nameZh: '腿举',
    nameEn: 'Leg Press',
    type: 'strength',
    primaryMuscleGroup: 'legs',
    secondaryMuscleGroups: [],
    equipment: 'machine',
    description: '器械下肢推蹬动作，主要训练腿部。',
    imageUri: null,
    sourceName: STARTER_EXERCISE_SOURCE_NAME,
    sourceReference: STARTER_EXERCISE_SEED_VERSION,
    license: STARTER_EXERCISE_LICENSE,
    status: 'active',
    createdAt: '2026-07-15T00:00:00.000Z',
    updatedAt: '2026-07-15T00:00:00.000Z',
  },
] as const satisfies readonly ExerciseSeedRow[];
